{
  "acts": [
    "ACT.UNDERDOCKS",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 7,
  "build_id": "v0.107.1",
  "game_mode": "daily",
  "killed_by_encounter": "NONE.NONE",
  "killed_by_event": "EVENT.NEOW",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.REGRET"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.REGRET"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.REGRET"
              },
              {
                "id": "CARD.TURBO"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.TURBO"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.TURBO"
              },
              {
                "id": "CARD.TURBO"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.TURBO"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.TURBO"
              },
              {
                "id": "CARD.TURBO"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.TURBO"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.TURBO"
              },
              {
                "id": "CARD.TURBO"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.TURBO"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.TURBO"
              },
              {
                "id": "CARD.TURBO"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.TURBO"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.TURBO"
              }
            ],
            "current_gold": 99,
            "current_hp": 0,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SPECIALIZED.title",
                  "table": "modifiers"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 60,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      }
    ]
  ],
  "modifiers": [
    {
      "id": "MODIFIER.SPECIALIZED"
    },
    {
      "id": "MODIFIER.HOARDER"
    },
    {
      "id": "MODIFIER.CURSED_RUN"
    }
  ],
  "platform_type": "steam",
  "players": [
    {
      "badges": [],
      "character": "CHARACTER.DEFECT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ZAP"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DUALCAST"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.REGRET"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.REGRET"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.REGRET"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.TURBO"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.TURBO"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.TURBO"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.TURBO"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.TURBO"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.TURBO"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.TURBO"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.TURBO"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.TURBO"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.TURBO"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.TURBO"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.TURBO"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.TURBO"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.TURBO"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.TURBO"
        }
      ],
      "id": 1,
      "max_potion_slot_count": 2,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.CRACKED_CORE"
        }
      ]
    }
  ],
  "run_time": 15,
  "schema_version": 9,
  "seed": "27_07_2026_1P",
  "start_time": 1785170302,
  "was_abandoned": true,
  "win": false
}